### ISSUE TITLE
How to format several fields from querying mongo

### ISSUE THREAD

**Issue by RogelioGaytan** [Aldaviva/mongoose-moment#3]
How would I parse a query result from mongo?

At the instrucctions you say

> Reading models
>     var myModel = MyModel.findById('123', function(err, doc){
>     console.log(doc.created.format());
> });

BUt supose you have a model with several fields like:

`var mySchema = new mongoose.Schema({`
`Name: String,`
`created: 'Moment'`
`Street :String`
`});`

How woud you parse internaly each created field for every row in my mongo db database?

In your example you only do a console.log for one registry but what por a query for a full collection in mongo?

`var mySchema = MyEschema.find().exec( function(err, list){`
`response.json(list)`
`});`

**Comment by Aldaviva** [comment]
Hi,

I hope I understand your question correctly.

If you want to change how all of your moments are serialized into JSON, you can [override `moment.fn.toJSON()`](http://momentjs.com/docs/#/displaying/as-json/):

``` javascript
moment.fn.toJSON = function(){
    return this.format("LLLL");
}
```

which results in

``` json
[
    {
        "Name": "my name",
        "created": "Thursday, September 4 1986 8:30 PM",
        "Street": "my street"
    }
]
```

## 

Alternately, if you want more fine-grained control of moment JSON serialization on a per-response basis, you can use [`Array.prototype.map()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map):

``` javascript
var mySchema = MyEschema.find().exec( function(err, list){
    response.json(list.map(function(item){
        if(moment.isMoment(item.created)){
            item.created = item.created.format("LLLL");
        }
        return item;
    });
});
```

which also results in

``` json
[
    {
        "Name": "my name",
        "created": "Thursday, September 4 1986 8:30 PM",
        "Street": "my street"
    }
]
```

I hope this is helpful.

**Comment by RogelioGaytan** [comment]
THank you very much, i'll try that.
